sudo: required

notifications:
  email:
    on_success: always
    on_failure: always

language: cpp

compiler: gcc

dist: bionic

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - wget https://syncandshare.lrz.de/dl/fiJNAokgbe2vNU66Ru17DAjT/netcdf-4.6.1.tar.gz
 - wget https://github.com/hfp/libxsmm/archive/master.zip
 - cp -r $TRAVIS_BUILD_DIR/submodules/yaml-cpp .

install:
 - |
    sudo apt-get update
    sudo apt-get install gcc-8 g++-8 gfortran-8
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100
    sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-8 100
    gcc --version
    sudo apt-get install -qq openmpi-bin openmpi-common libopenmpi-dev hdf5-tools libhdf5-openmpi-100 libhdf5-openmpi-dev python3 python3-pip libmetis-dev libparmetis-dev cxxtest
    gfortran --version
 - sudo pip3 install --upgrade pip
 - sudo pip3 install 'numpy>=1.12.0'
 - sudo pip3 install lxml
 - sudo pip3 install setuptools
 - sudo pip3 install sphinx
 - sudo pip3 install sphinx_rtd_theme
 - sudo pip3 install gemmforge
 - cd yaml-cpp && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DYAML_CPP_BUILD_TOOLS=OFF -DYAML_CPP_BUILD_TESTS=OFF . && make && sudo make install && cd ..
 - tar -xaf netcdf-4.6.1.tar.gz
 - cd netcdf-4.6.1 && CC=h5pcc ./configure --prefix=/usr --enable-shared=no --disable-dap && make && sudo make install && cd ..
 - unzip master.zip
 - cd libxsmm-master && make generator && sudo cp bin/libxsmm_gemm_generator /usr/bin && cd ..

env:
  - SEISSOL_BUILD_TYPE=Debug SEISSOL_PRECISION=double
  - SEISSOL_BUILD_TYPE=Debug SEISSOL_PRECISION=single
  - SEISSOL_BUILD_TYPE=Release SEISSOL_PRECISION=double
  - SEISSOL_BUILD_TYPE=Release SEISSOL_PRECISION=single

# Defines 4 jobs i.e., Debug and Release x Double and Single
script:
 - cd Documentation && make html && cd ..
 - |
   set -euo pipefail
   export IFS=$'\n\t'
   export CTEST_OUTPUT_ON_FAILURE=1
   for equation in elastic viscoelastic2 anisotropic poroelastic; do
    if [ "$equation" = viscoelastic2 ]; then
        mechanisms=3
    else
        mechanisms=0
    fi
        dirname="build_${equation}_${SEISSOL_PRECISION}_${SEISSOL_BUILD_TYPE}"
        echo "mkdir ${dirname}"
        mkdir -p $dirname && cd $dirname
        CMAKE_PREFIX_PATH=~ PKG_CONFIG_PATH=~/lib/pkgconfig/: cmake -DNETCDF=OFF -DMETIS=ON -DCOMMTHREAD=ON -DASAGI=OFF -DHDF5=ON -DCMAKE_BUILD_TYPE=$SEISSOL_BUILD_TYPE -DTESTING=ON -DLOG_LEVEL=warning -DLOG_LEVEL_MASTER=info -DHOST_ARCH=hsw -DPRECISION=$SEISSOL_PRECISION -DEQUATIONS=$equation -DNUMBER_OF_MECHANISMS=$mechanisms -DGEMM_TOOLS_LIST=LIBXSMM ..
        make -j $(nproc)
        make test
        cd ..
    done
    set +u
