jobs:
  - job:
    displayName: seissol-documentation
    pool:
      vmImage: 'ubuntu-22.04'
    steps:
      - bash: |
          set -euo pipefail
          export IFS=$'\n\t'
          sudo apt-get update
          sudo apt-get install -qq python3 python3-pip
          sudo pip3 install --upgrade pip
          sudo pip3 install sphinx
          sudo pip3 install sphinx_rtd_theme
          cd Documentation && make html && cd ..

